version: '3.9'

services:
 web:
  build:
   context: .
  ports:
   - 5000:5000
  environment:
    PORT: 5000
  volumes:
   - ./:/app
  depends_on: 
   - db
  networks:
   - postgres

 db:
  image: postgres
  restart: always
  ports:
   - 5432:5432
  environment:      
    POSTGRES_DB: $DB_NAME
    POSTGRES_USER: $DB_USER
    POSTGRES_PASSWORD: $DB_PASSWORD
    PGDATA: /var/lib/postgresql/data
  volumes:
   - postgres:/var/lib/postgresql/data
  networks:
   - postgres

 adminer:
  image: adminer
  restart: always
  ports:
   - 8080:8080
  depends_on: 
   - db
  networks:
   - postgres

networks:
 postgres:
  driver: bridge

volumes:
  postgres:

